### ISSUE TITLE
Copy kerning from Upercase to Small Caps Error

### ISSUE THREAD

**Issue by natenine** [mekkablue/Glyphs-Scripts#35]
Hi, 

I get this error when I try to run the script:

Copying Kerning from UC to SC...
Font: (font name)
Master: (master weight)

  Added @a.sc @e.sc -26.0
Traceback (most recent call last):
  File "<string>", line 123, in <module>
NameError: name 'scKernValue' is not defined

**Comment by weiweihuanghuang** [comment]
I get the following
```
Traceback (most recent call last):
  File "Copy kerning from Caps to SC.py", line 78, in <module>
    for LeftKey in masterKernDict.keys():
TypeError: 'list' object is not callable
```

**Comment by mekkablue** [comment]
I fixed it but github won't let me upload it. Meanwhile, you can go to that line an change scKernValue to kernValue.

**Comment by natenine** [comment]
Thanks @mekkablue, but it's still not happening. Now a different error:

Traceback (most recent call last):
  File "<string>", line 78, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/PyObjC/objc/_convenience.py", line 582, in enumeratorGenerator
    yield container_unwrap(anEnumerator.nextObject(), StopIteration)
objc.error: NSGenericException - *** Collection <__NSArrayM: 0x608002047c20> was mutated while being enumerated.

**Comment by mekkablue** [comment]
Which versions of app, OS are you running?

**Comment by natenine** [comment]
OS 10.9.5
Glyphs Version 1.4.3 (586)

**Comment by mekkablue** [comment]
Update to 1.4.5 (activate cutting edge in app prefs> updates)

**Comment by natenine** [comment]
how can i update to 1.4.5? I have the app store version

**Comment by mekkablue** [comment]
Then you cannot update to cutting edge versions. Doesn't matter for the script. Looking at it, I realize it is not fished yet, and I uploaded it too soon. Sorry, but I need to pull it. Check back at a later time please.
